import Joi from "joi";
export const caseStudyTemplate2Schema = Joi.object({
  nameEn: Joi.string().allow("", null),
  nameAr: Joi.string().allow("", null),
  seoDescriptionEn: Joi.string().allow("", null),
  seoDescriptionAr: Joi.string().allow("", null),
  isActive: Joi.boolean().default(true),
  headingEn: Joi.string().allow("", null),
  headingAr: Joi.string().allow("", null),
  description1En: Joi.string().allow("", null),
  description1Ar: Joi.string().allow("", null),
  description2En: Joi.string().allow("", null),
  description2Ar: Joi.string().allow("", null),
  description3En: Joi.string().allow("", null),
  description3Ar: Joi.string().allow("", null),
  description4En: Joi.string().allow("", null),
  description4Ar: Joi.string().allow("", null),
  image1: Joi.string().allow("", null),
  image2: Joi.string().allow("", null),
  image3: Joi.string().allow("", null),
  resultImpactEn: Joi.string().allow("", null),
  resultImpactAr: Joi.string().allow("", null),
  technologiesUsedEn: Joi.string().allow("", null),
  technologiesUsedAr: Joi.string().allow("", null),
  pageId: Joi.string().allow("", null),
});
